version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: /deploy
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker-compose
    directory: /src/test/resources
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
